name: Checkout

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress build
        id: cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          build: npm run test
          browser: chrome

    
